### PR TITLE
Josh branch

### PR DESCRIPTION
**Pull request by jszacha1**

### CODE REVIEW

**Comment by szaman19** [comment]
@andygrace227 This looks like it touches your DynamicMatrix class. I don't think we can merge this in as it is because it would delete them. 

Josh, you should delete the venv from the PR. That shouldn't be tracked.

**Review by andygrace227 — APPROVED** [review]
Looks fine to me

**Review by szaman19 — APPROVED** [review]

**Comment by szaman19** [comment]
OOF, 40k new added lines. Too much to review. Probably includes a lot of unneeded files, so we'll refactor that later. Merging in for now.

**Comment by szaman19** [comment]
I think everyone's moved on to their own forks, so deleting this branch @jszacha1 @andygrace227

**Pull request merged**
